import Head from 'next/head'
import Image from 'next/image'
import * as Popover from "@radix-ui/react-popover";
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Popover.Root>
          <Popover.Trigger>Trigger</Popover.Trigger>
          <Popover.Content className={styles.popover} sideOffset={4}>
            hello
          </Popover.Content>
        </Popover.Root>
    </div>
  )
}
